name: CI - Backend

on:
  push:
    branches:
      - master
      - "**"
      - "chore/ci-initial"
  pull_request:
    branches:
      - master

jobs:
  test-auth:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
      ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
      REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Run Auth tests
        run: npm test -- tests/auth

  test-products:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
      ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
      REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Run Product tests
        run: npm test -- tests/products